# Generated by Django 4.2.3 on 2023-07-18 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to=file.models.file_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, unique=True, upload_to='thumbnails/')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(max_length=400)),
                ('uploaded', models.BooleanField(default=False)),
                ('shared', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploaded_by_user', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
