# Generated by Django 4.2.3 on 2023-08-08 05:36

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_rename_users_file_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='description',
        ),
        migrations.AlterField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=file.models.thumbnail_file_path),
        ),
    ]
