export const FILE_ADD_REQUEST = 'FILE_ADD_REQUEST'
export const FILE_ADD_SUCCESS = 'FILE_ADD_SUCCESS'
export const FILE_ADD_FAIL = 'FILE_ADD_FAIL'

export const FILES_GET_REQUEST = 'FILES_GET_REQUEST'
export const FILES_GET_SUCCESS = 'FILES_GET_SUCCESS'
export const FILES_GET_FAIL = 'FILES_GET_FAIL'

export const FILE_GET_REQUEST = 'FILE_GET_REQUEST'
export const FILE_GET_SUCCESS = 'FILE_GET_SUCCESS'
export const FILE_GET_FAIL = 'FILE_GET_FAIL'

export const FILE_CHANGE_REQUEST = 'FILE_CHANGE_REQUEST'
export const FILE_CHANGE_SUCCESS = 'FILE_CHANGE_SUCCESS'
export const FILE_CHANGE_FAIL = 'FILE_CHANGE_FAIL'

export const FILE_DELETE_REQUEST = 'FILE_DELETE_REQUEST'
export const FILE_DELETE_SUCCESS = 'FILE_DELETE_SUCCESS'
export const FILE_DELETE_FAIL = 'FILE_DELETE_FAIL'

export const SHARE_FILE_REQUEST = 'SHARE_FILE_REQUEST'
export const SHARE_FILE_SUCCESS = 'SHARE_FILE_SUCCESS'
export const SHARE_FILE_FAIL = 'SHARE_FILE_FAIL'

export const DOWNLOAD_FILE_REQUEST = 'DOWNLOAD_FILE_REQUEST'
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS'
export const DOWNLOAD_FILE_FAIL = 'DOWNLOAD_FILE_FAIL'

export const FILE_DATA_RESET = 'FILE_DATA_RESET'
