export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USERS_DETAIL_REQUEST = 'USERS_DETAIL_REQUEST'
export const USERS_DETAIL_SUCCESS = 'USERS_DETAIL_SUCCESS'
export const USERS_DETAIL_FAIL = 'USERS_DETAIL_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'
